### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by Webbanditten** [oliverwk/lngr#1]
Hi

You might want to make this repository private or remove your bearer token from the code and git history.

https://github.com/oliverwk/lngr/blob/95e71b542e795d39b627368a93f9c426bb26a356/OpenLocker%20WatchKit%20Extension/LockerManager.swift#L42

Right now it's possible for anyone to open your locker via the Releezeme API.

**Comment by oliverwk** [comment]
Thanks for noticing, the request was failing many times that day so by the time it was done i wanted to move on.
I made the repo privat (just in case it happens again) and changed the code so it loads the credentials from a file.
